export const enum IAttribute {
  一般 = '一般',
  格斗 = '格斗',
  飞行 = '飞行',
  毒 = '毒',
  地面 = '地面',
  岩石 = '岩石',
  虫 = '虫',
  幽灵 = '幽灵',
  钢 = '钢',
  火 = '火',
  水 = '水',
  草 = '草',
  电 = '电',
  超能力 = '超能力',
  冰 = '冰',
  龙 = '龙',
  恶 = '恶',
  妖精 = '妖精',
}

export const allAttr: IAttribute[] = [
  IAttribute.一般,
  IAttribute.格斗,
  IAttribute.飞行,
  IAttribute.毒,
  IAttribute.地面,
  IAttribute.岩石,
  IAttribute.虫,
  IAttribute.幽灵,
  IAttribute.钢,
  IAttribute.火,
  IAttribute.水,
  IAttribute.草,
  IAttribute.电,
  IAttribute.超能力,
  IAttribute.冰,
  IAttribute.龙,
  IAttribute.恶,
  IAttribute.妖精,
];

export const attributeColorMap: Record<IAttribute, string> = {
  [IAttribute.一般]: '#9fa19f',
  [IAttribute.格斗]: '#ff8000',
  [IAttribute.飞行]: '#81b9ef',
  [IAttribute.毒]: '#9141cb',
  [IAttribute.地面]: '#915121',
  [IAttribute.岩石]: '#afa981',
  [IAttribute.虫]: '#91a119',
  [IAttribute.幽灵]: '#704170',
  [IAttribute.钢]: '#60a1b8',
  [IAttribute.火]: '#e62829',
  [IAttribute.水]: '#2980ef',
  [IAttribute.草]: '#3fa129',
  [IAttribute.电]: '#fac000',
  [IAttribute.超能力]: '#ef4179',
  [IAttribute.冰]: '#3fd8ff',
  [IAttribute.龙]: '#5060e1',
  [IAttribute.恶]: '#50413f',
  [IAttribute.妖精]: '#ef70ef',
};

export const damageRateMap: Record<IAttribute, Record<IAttribute, number>> = {
  [IAttribute.一般]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1 / 2,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 0,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.格斗]: {
    [IAttribute.一般]: 2,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1 / 2,
    [IAttribute.毒]: 1 / 2,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 2,
    [IAttribute.虫]: 1 / 2,
    [IAttribute.幽灵]: 0,
    [IAttribute.钢]: 2,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1 / 2,
    [IAttribute.冰]: 2,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 2,
    [IAttribute.妖精]: 1 / 2,
  },
  [IAttribute.飞行]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 2,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1 / 2,
    [IAttribute.虫]: 2,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 2,
    [IAttribute.电]: 1 / 2,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.毒]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1 / 2,
    [IAttribute.地面]: 1 / 2,
    [IAttribute.岩石]: 1 / 2,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1 / 2,
    [IAttribute.钢]: 0,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 2,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 2,
  },
  [IAttribute.地面]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 0,
    [IAttribute.毒]: 2,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 2,
    [IAttribute.虫]: 1 / 2,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 2,
    [IAttribute.火]: 2,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1 / 2,
    [IAttribute.电]: 2,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.岩石]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1 / 2,
    [IAttribute.飞行]: 2,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1 / 2,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 2,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 2,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 2,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.虫]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1 / 2,
    [IAttribute.飞行]: 1 / 2,
    [IAttribute.毒]: 1 / 2,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1 / 2,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1 / 2,
    [IAttribute.水]: 1,
    [IAttribute.草]: 2,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 2,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 2,
    [IAttribute.妖精]: 1 / 2,
  },
  [IAttribute.幽灵]: {
    [IAttribute.一般]: 0,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 2,
    [IAttribute.钢]: 1,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 2,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1 / 2,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.钢]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 2,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1 / 2,
    [IAttribute.水]: 1 / 2,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1 / 2,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 2,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 2,
  },
  [IAttribute.火]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1 / 2,
    [IAttribute.虫]: 2,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 2,
    [IAttribute.火]: 1 / 2,
    [IAttribute.水]: 1 / 2,
    [IAttribute.草]: 2,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 2,
    [IAttribute.龙]: 1 / 2,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.水]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 2,
    [IAttribute.岩石]: 2,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1,
    [IAttribute.火]: 2,
    [IAttribute.水]: 1 / 2,
    [IAttribute.草]: 1 / 2,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1 / 2,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.草]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1 / 2,
    [IAttribute.毒]: 1 / 2,
    [IAttribute.地面]: 2,
    [IAttribute.岩石]: 2,
    [IAttribute.虫]: 1 / 2,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1 / 2,
    [IAttribute.水]: 2,
    [IAttribute.草]: 1 / 2,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1 / 2,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.电]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 2,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 0,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1,
    [IAttribute.火]: 1,
    [IAttribute.水]: 2,
    [IAttribute.草]: 1 / 2,
    [IAttribute.电]: 1 / 2,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1 / 2,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.超能力]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 2,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 2,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1 / 2,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 0,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.冰]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 2,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 2,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1 / 2,
    [IAttribute.水]: 1 / 2,
    [IAttribute.草]: 2,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1 / 2,
    [IAttribute.龙]: 2,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 1,
  },
  [IAttribute.龙]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 2,
    [IAttribute.恶]: 1,
    [IAttribute.妖精]: 0,
  },
  [IAttribute.恶]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 1 / 2,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 2,
    [IAttribute.钢]: 1,
    [IAttribute.火]: 1,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 2,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 1,
    [IAttribute.恶]: 1 / 2,
    [IAttribute.妖精]: 1 / 2,
  },
  [IAttribute.妖精]: {
    [IAttribute.一般]: 1,
    [IAttribute.格斗]: 2,
    [IAttribute.飞行]: 1,
    [IAttribute.毒]: 1 / 2,
    [IAttribute.地面]: 1,
    [IAttribute.岩石]: 1,
    [IAttribute.虫]: 1,
    [IAttribute.幽灵]: 1,
    [IAttribute.钢]: 1 / 2,
    [IAttribute.火]: 1 / 2,
    [IAttribute.水]: 1,
    [IAttribute.草]: 1,
    [IAttribute.电]: 1,
    [IAttribute.超能力]: 1,
    [IAttribute.冰]: 1,
    [IAttribute.龙]: 2,
    [IAttribute.恶]: 2,
    [IAttribute.妖精]: 1,
  },
};
